version: '3.8'
services:

  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    depends_on:
      - app
      - watchtower
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        PUBLIC_SITE_NAME: ${PUBLIC_SITE_NAME}
        PUBLIC_SHORT_SITE_NAME: ${PUBLIC_SHORT_SITE_NAME}
        PUBLIC_SITE_DESCRIPTION: ${PUBLIC_SITE_DESCRIPTION}
        PUBLIC_SITE_TITLE: ${PUBLIC_SITE_TITLE}
        SECRET_DATABASE_URL: ${SECRET_DATABASE_URL}
        SECRET_DATABASE_PORT: ${SECRET_DATABASE_PORT}
        SECRET_DATABASE_NAME: ${SECRET_DATABASE_NAME}
        SECRET_DATABASE_USER: ${SECRET_DATABASE_USER}
        SECRET_DATABASE_PASSWORD: ${SECRET_DATABASE_PASSWORD}
        SECRET_ADMIN_USERNAME: ${SECRET_ADMIN_USERNAME}
        SECRET_ADMIN_PASSWORD: ${SECRET_ADMIN_PASSWORD}
        SECRET_CLOUDFLARE_ACCESS_KEY_ID: ${SECRET_CLOUDFLARE_ACCESS_KEY_ID}
        SECRET_CLOUDFLARE_ACCESS_KEY: ${SECRET_CLOUDFLARE_ACCESS_KEY}
        SECRET_CLOUDFLARE_TOKEN_VALUE: ${SECRET_CLOUDFLARE_TOKEN_VALUE}
        SECRET_CLOUDFLARE_ENDPOINT: ${SECRET_CLOUDFLARE_ENDPOINT}
        SECRET_CLOUDFLARE_BUCKET_NAME: ${SECRET_CLOUDFLARE_BUCKET_NAME}
        SECRET_CLOUDFLARE_BUCKET_URL: ${SECRET_CLOUDFLARE_BUCKET_URL}
        CHROMEBOOK_ONLY_MODE: ${CHROMEBOOK_ONLY_MODE}
        PUBLIC_ADSENSE_CLIENT_ID: ${PUBLIC_ADSENSE_CLIENT_ID}
        PUBLIC_ADSENSE_GAME_SIDES_SLOT_ID: ${PUBLIC_ADSENSE_GAME_SIDES_SLOT_ID}

    env_file:
      - .env

    environment:
      - VIRTUAL_HOST:${VIRTUAL_HOST_DOMAIN}

    networks:
      - default

    ports:
      - "3000:3000"
    
    restart: on-failure

networks:
  default:
    driver: bridge